services:
  db:
    image: postgres:alpine
    container_name: bb-db
    ports:
      - 5555:5432
    volumes:
      - budgetbuddy-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=budgetbuddy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d budgetbuddy"]
      interval: 5s
      timeout: 5s
      retries: 10
  eureka:
    build: ./services/Budget-Buddy-DiscoveryService
    container_name: bb-eureka
    ports:
      - 8761:8761
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider -q http://localhost:8761/actuator/health || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
  gateway:
    build: ./services/Budget-Buddy-GatewayService
    container_name: bb-gateway
    ports:
      - 8125:8125
    environment:
      - FRONTEND_URL=http://127.0.0.1:5173
      - EUREKA_URL=http://host.docker.internal:8761/eureka
    depends_on:
      db:
        condition: service_healthy
      eureka:
        condition: service_healthy
  accounts:
    build: ./services/Budget-Buddy-AccountService
    container_name: bb-accounts
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://host.docker.internal:5555/budgetbuddy
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - EUREKA_URL=http://host.docker.internal:8761/eureka
    depends_on:
      db:
        condition: service_healthy
      eureka:
        condition: service_healthy
  auth:
    build: ./services/Budget-Buddy-AuthService
    container_name: bb-auth
    ports:
      - 8888:8888
    environment:
      - DATABASE_URL=jdbc:postgresql://host.docker.internal:5555/budgetbuddy
      - DATABASE_USER=postgres
      - DATABASE_PASS=password
      - EUREKA_URL=http://host.docker.internal:8761/eureka
    depends_on:
      db:
        condition: service_healthy
      eureka:
        condition: service_healthy
  budgets:
    build: ./services/Budget-Buddy-BudgetService/budget-service
    container_name: bb-budgets
    ports:
      - 8082:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://host.docker.internal:5555/budgetbuddy
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - EUREKA_URL=http://host.docker.internal:8761/eureka
    depends_on:
      db:
        condition: service_healthy
      eureka:
        condition: service_healthy
  tax:
    build: ./services/Budget-Buddy-TaxService
    container_name: bb-tax
    ports:
      - 8084:8084
    environment:
      - DATABASE_URL=jdbc:postgresql://host.docker.internal:5555/budgetbuddy
      - DATABASE_USER=postgres
      - DATABASE_PASS=password
      - EUREKA_URL=http://host.docker.internal:8761/eureka
    depends_on:
      db:
        condition: service_healthy
      eureka:
        condition: service_healthy
  users:
    build: ./services/Budget-Buddy-UserService
    container_name: bb-users
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=jdbc:postgresql://host.docker.internal:5555/budgetbuddy
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - EUREKA_URL=http://host.docker.internal:8761/eureka
    depends_on:
      db:
        condition: service_healthy
      eureka:
        condition: service_healthy
  transactions:
    build: ./services/Budget-Buddy-TransactionService
    container_name: bb-transactions
    ports:
      - 8083:8083
    environment:
      - DATABASE_URL=jdbc:postgresql://host.docker.internal:5555/budgetbuddy
      - DATABASE_USER=postgres
      - DATABASE_PASS=password
      - EUREKA_URL=http://host.docker.internal:8761/eureka
    depends_on:
      db:
        condition: service_healthy
      eureka:
        condition: service_healthy
  frontend:
    build: ./services/frontend
    container_name: bb-frontend
    ports:
      - 5173:5173

volumes:
  budgetbuddy-data:
